#!/usr/bin/env python
"""
Multi-FR Pipeline Runner

여러 FR 을 고려한 복합 시나리오 TC 를 생성하고 검증합니다.

Usage:
    # COM rAPP 의 여러 FR 에 대한 복합 TC 생성
    python scripts/run_multi_fr_pipeline.py \
        --fr-list FR10.COA.SR1.10 FR10.COA.SR1.11 \
        --pkg SVR26A \
        --rapp COM \
        --scenario-type simultaneous

    # 기존 TC 에 대해 Multi-FR Review 수행
    python scripts/run_multi_fr_pipeline.py \
        --tc-path output/enhanced_tc/TC_v1.md \
        --fr-list FR10.COA.SR1.10 FR10.COA.SR1.11 \
        --review-only
"""

import argparse
import logging
import sys
from datetime import datetime
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from tc_reviewer.multi_fr_reviewer import MultiFRReviewer, MultiFRReviewResult

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[
        logging.FileHandler(
            f"output/multi_fr_pipeline_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log",
            encoding="utf-8"
        ),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


def generate_multi_fr_tc(
    fr_list: list[str],
    sw_pkg: str,
    rapp: str,
    scenario_type: str = "simultaneous"
) -> str:
    """
    여러 FR 에 대한 복합 TC 생성 (템플릿 기반)
    
    Args:
        fr_list: FR ID 목록
        sw_pkg: SW Package
        rapp: rAPP 이름
        scenario_type: 시나리오 유형 (simultaneous, sequential, trade_off)
    
    Returns:
        생성된 TC 마크다운 문자열
    """
    logger.info(f"Generating Multi-FR TC for {len(fr_list)} FRs")
    
    # FR 목록 포맷팅
    fr_list_str = ", ".join(fr_list)
    
    # 시나리오 유형별 템플릿
    if scenario_type == "simultaneous":
        scenario_desc = "여러 FR 조건이 동시에 발생하는 상황"
        test_focus = "우선순위 규칙에 따른 처리 순서"
    elif scenario_type == "sequential":
        scenario_desc = "여러 FR 조건이 시간 순서대로 발생하는 상황"
        test_focus = "각 FR 이 순차적으로 올바르게 처리되는지"
    elif scenario_type == "trade_off":
        scenario_desc = "한 FR 해결이 다른 FR 문제를 악화시키는 Trade-off 상황"
        test_focus = "Trade-off 관계가 로그에 기록되고 다음 cycle 에서 처리되는지"
    else:
        scenario_desc = "복합 FR 상황"
        test_focus = "복합 시나리오 검증"
    
    tc_content = f"""# Test Case: Multi-FR Scenario ({scenario_type})

## 생성 정보
- **Feature IDs**: {fr_list_str}
- **SW Package**: {sw_pkg}
- **rAPP**: {rapp}
- **시나리오 유형**: {scenario_type}
- **생성일**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **생성 방식**: Multi-FR Pipeline

---

## 1. Test Overview

본 TC 는 {scenario_desc} 에서 우선순위 규칙과 충돌 해결 메커니즘이 올바르게 동작하는지 검증합니다.

**Test Focus**: {test_focus}

---

## 2. Test Purpose

1. **FR 의존성 검증**: 모든 의존 FR 이 TC 에 포함되었는지
2. **우선순위 규칙 검증**: 충돌 시 우선순위가 높은 FR 이 먼저 처리되는지
3. **Trade-off 처리**: 상충되는 액션이 올바르게 해결되는지
4. **복합 시나리오**: 동시/순차 발생 상황에서의 동작 검증

---

## 3. Related Features

| FR ID | Name | Priority | Conflicts With |
|-------|------|----------|----------------|
"""
    
    # FR 정보 추가 (Placeholder - 실제 구현 시 Dependency Graph 에서 조회)
    for fr_id in fr_list:
        tc_content += f"| {fr_id} | (FR name) | - | - |\n"
    
    tc_content += f"""
---

## 4. Precondition

### 4.1 환경 구성
| 항목 | 설정값 |
|------|--------|
| **SW Package** | {sw_pkg} |
| **rAPP** | {rapp} |
| **Analytic Server** | 정상 동작 중 |

### 4.2 FR 조건 설정
"""
    
    # 각 FR 별 조건 추가
    for i, fr_id in enumerate(fr_list, 1):
        tc_content += f"""
#### FR #{i}: {fr_id}
- **조건**: (FR specific condition)
- **Trigger**: (Trigger condition)
- **Expected Action**: (Resolution action)
"""
    
    tc_content += f"""
---

## 5. Test Procedure

### TC_01: {scenario_type.capitalize()} Scenario

#### 5.1.1 Precondition
- 모든 FR 의 trigger 조건을 만족하는 상태
- 우선순위 규칙에 따라 처리될 것으로 예상

#### 5.1.2 Test Steps
1. Analytic Server 에서 COM 알고리즘 실행
2. 여러 FR 조건이 동시에/순차적으로 발생
3. 시스템의 처리 순서 확인
4. 로그에 우선순위 규칙 적용 기록 확인
5. Trade-off 관계인 경우 로그 기록 확인

#### 5.1.3 Expected Result
- 우선순위가 높은 FR 이 먼저 처리됨
- 충돌 해결 규칙이 올바르게 적용됨
- Trade-off 관계가 로그에 기록됨
- 각 FR 의 KPI 가 개선됨

---

## 6. Pass/Fail Criteria

| TC ID | Pass Criteria | Fail Criteria |
|-------|---------------|---------------|
| TC_01 | 우선순위 규칙에 따라 처리됨 | 우선순위 규칙 위반 |
| TC_01 | 충돌 해결 규칙이 적용됨 | 충돌 미해결 |
| TC_01 | Trade-off 관계 로그 기록 | Trade-off 미기록 |

---

## 7. Human Review Required

> ⚠️ 다음 항목은 실무자의 확인이 필요합니다:

1. **FR 우선순위**: 현재 설정된 우선순위가 적절한지
2. **Trade-off 처리**: Trade-off 관계일 때 다음 cycle 처리가 올바른지
3. **KPI 개선 기준**: 각 FR 의 KPI 개선 기준이 적절한지

---

## 8. Multi-FR Review Result

> 이 섹션은 Multi-FR Review 실행 후 자동 생성됩니다.

- **Quality Score**: (자동 생성)
- **Risk Level**: (자동 생성)
- **Decision**: (자동 생성)
- **Findings**: (자동 생성)

---

## 9. Change Log

| 버전 | 변경일 | 변경 내용 |
|------|--------|-----------|
| v1.0 | {datetime.now().strftime('%Y-%m-%d')} | Multi-FR TC 초안 생성 |

---

**Generated by**: RAS-TestCaseReview Multi-FR Pipeline  
**Dependency Graph**: references/com_fr_dependency.json
"""
    
    return tc_content


def run_review(
    tc_path: Path,
    fr_list: list[str],
    dependency_graph_path: Path
) -> MultiFRReviewResult:
    """
    TC 에 대해 Multi-FR Review 수행
    
    Args:
        tc_path: TC 파일 경로
        fr_list: FR ID 목록
        dependency_graph_path: FR Dependency Graph 경로
    
    Returns:
        MultiFRReviewResult
    """
    logger.info(f"Running Multi-FR Review for {tc_path}")
    
    reviewer = MultiFRReviewer(dependency_graph_path)
    result = reviewer.review(tc_path, fr_list)
    
    return result


def save_review_report(
    result: MultiFRReviewResult,
    output_dir: Path
) -> Path:
    """Review Report 저장"""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    report_path = output_dir / f"multi_fr_review_{result.feature_id}_{timestamp}.md"
    
    report_content = f"""# Multi-FR Review Report

## Review Information
- **Feature ID**: {result.feature_id}
- **SW Package**: {result.sw_package}
- **rAPP**: {result.rapp_name}
- **Review Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Involved FRs**: {', '.join(result.involved_frs)}

---

## Quality Score

| Metric | Value |
|--------|-------|
| **Overall Score** | {result.quality_score:.1f}/100 |
| **Risk Level** | {result.risk_level} |
| **Decision** | {result.decision} |
| **Confidence** | {result.confidence:.2f} |

---

## Review Summary

### Findings
- **Total Findings**: {len(result.findings)}
- **Missing Dependencies**: {len(result.missing_dependencies)}
- **Priority Violations**: {len(result.priority_violations)}
- **Trade-off Scenarios**: {len(result.trade_off_scenarios)}

---

## Detailed Findings

"""
    
    for i, finding in enumerate(result.findings, 1):
        report_content += f"""
### Finding #{i}: {finding.check_id}

- **Category**: {finding.category}
- **Severity**: {finding.severity}
- **Description**: {finding.description}
- **Involved FRs**: {', '.join(finding.involved_frs)}
- **TC Section**: {finding.tc_section}
- **Suggestion**: {finding.suggestion}

"""
    
    if result.missing_dependencies:
        report_content += f"""
## Missing Dependencies

{', '.join(result.missing_dependencies)}

"""
    
    if result.priority_violations:
        report_content += f"""
## Priority Violations

{', '.join(result.priority_violations)}

"""
    
    if result.trade_off_scenarios:
        report_content += f"""
## Trade-off Scenarios

| FR1 | Action | FR2 | Action | Side Effect |
|-----|--------|-----|--------|-------------|
"""
        for to in result.trade_off_scenarios:
            report_content += f"| {to['fr1']} | {to['fr1_action']} | {to['fr2']} | {to['fr2_action']} | {to['side_effect']} |\n"
    
    report_content += f"""
---

**Report Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  
**Review Tool**: RAS-TestCaseReview Multi-FR Pipeline
"""
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
    
    logger.info(f"Review Report saved to: {report_path}")
    
    return report_path


def main():
    """Main pipeline entry point"""
    parser = argparse.ArgumentParser(description="Multi-FR Pipeline Runner")
    parser.add_argument(
        "--fr-list",
        type=str,
        nargs="+",
        required=True,
        help="FR ID 목록 (예: FR10.COA.SR1.10 FR10.COA.SR1.11)"
    )
    parser.add_argument(
        "--pkg",
        type=str,
        default="SVR26A",
        help="SW Package (예: SVR26A)"
    )
    parser.add_argument(
        "--rapp",
        type=str,
        default="COM",
        help="rAPP 이름 (예: COM)"
    )
    parser.add_argument(
        "--scenario-type",
        type=str,
        choices=["simultaneous", "sequential", "trade_off"],
        default="simultaneous",
        help="시나리오 유형"
    )
    parser.add_argument(
        "--tc-path",
        type=str,
        help="기존 TC 파일 경로 (review-only 모드)"
    )
    parser.add_argument(
        "--review-only",
        action="store_true",
        help="TC 생성 없이 Review 만 수행"
    )
    parser.add_argument(
        "--dep-graph",
        type=str,
        default="references/com_fr_dependency.json",
        help="FR Dependency Graph 경로"
    )
    
    args = parser.parse_args()
    
    logger.info("=" * 70)
    logger.info("Multi-FR Pipeline - Starting")
    logger.info("=" * 70)
    logger.info(f"FR List: {', '.join(args.fr_list)}")
    logger.info(f"Package: {args.pkg}")
    logger.info(f"rAPP: {args.rapp}")
    logger.info(f"Scenario Type: {args.scenario_type}")
    logger.info("=" * 70)
    
    dep_graph_path = Path(args.dep_graph)
    
    if not dep_graph_path.exists():
        logger.error(f"Dependency Graph not found: {dep_graph_path}")
        return 1
    
    # Review-only 모드
    if args.review_only and args.tc_path:
        tc_path = Path(args.tc_path)
        if not tc_path.exists():
            logger.error(f"TC file not found: {tc_path}")
            return 1
        
        result = run_review(tc_path, args.fr_list, dep_graph_path)
        report_path = save_review_report(result, Path("output/quality_reports"))
        
        logger.info("=" * 70)
        logger.info("Multi-FR Review Completed")
        logger.info("=" * 70)
        logger.info(f"Quality Score: {result.quality_score:.1f}/100")
        logger.info(f"Risk Level: {result.risk_level}")
        logger.info(f"Decision: {result.decision}")
        logger.info(f"Report: {report_path}")
        logger.info("=" * 70)
        
        return 0
    
    # TC 생성 모드
    logger.info("Generating Multi-FR TC...")
    tc_content = generate_multi_fr_tc(
        fr_list=args.fr_list,
        sw_pkg=args.pkg,
        rapp=args.rapp,
        scenario_type=args.scenario_type
    )
    
    # TC 저장
    output_dir = Path("output/enhanced_tc")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    fr_ids_str = "_".join([fr.replace(".", "_") for fr in args.fr_list])
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    tc_path = output_dir / f"MultiFR_{fr_ids_str}_{args.pkg}_TC_v1_{timestamp}.md"
    
    with open(tc_path, "w", encoding="utf-8") as f:
        f.write(tc_content)
    
    logger.info(f"TC saved to: {tc_path}")
    
    # 생성된 TC 에 대해 Review 수행
    logger.info("Running Multi-FR Review...")
    result = run_review(tc_path, args.fr_list, dep_graph_path)
    report_path = save_review_report(result, Path("output/quality_reports"))
    
    logger.info("=" * 70)
    logger.info("Multi-FR Pipeline Completed")
    logger.info("=" * 70)
    logger.info(f"TC: {tc_path}")
    logger.info(f"Review Report: {report_path}")
    logger.info(f"Quality Score: {result.quality_score:.1f}/100")
    logger.info(f"Decision: {result.decision}")
    logger.info("=" * 70)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
